"""Write src/game/ConditionNames.inc: the name of every condition function,
by id, read from CommonLibSSE's FUNCTION_DATA::FunctionID enum. The panel
prints a perk's conditions with it. Run again after the submodule moves:

    python tools/gen_condition_names.py
"""
import io
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
header = root / "extern/commonlibsse-ng/include/RE/T/TESCondition.h"
out = root / "src/game/ConditionNames.inc"

text = header.read_text(encoding="utf-8")
start = text.index("enum class FunctionID")
end = text.index("kTotal", start)
names = {}
for m in re.finditer(r"\bk(\w+) = (\d+),", text[start:end]):
    names[int(m.group(2))] = m.group(1)
count = max(names) + 1

lines = ["// Generated by tools/gen_condition_names.py from the library's",
         "// FUNCTION_DATA::FunctionID; do not edit. Indexed by function id.",
         f"inline constexpr std::array<const char *, {count}> kConditionNames{{{{"]
for i in range(count):
    lines.append(f'    "{names.get(i, "")}",')
lines.append("}};")
io.open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"{out}: {len(names)} names, {count} slots")
